# Generated by Django 5.2 on 2025-05-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='conduct_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
